local var_0_0 = class("LoginSceneConst")

var_0_0.DEFINE = {
	ACCOUNT_BTN = 10,
	TRANSCODE_ALERT_VIEW = 5,
	REGISTER_PANEL_VIEW = 2,
	BG_LAY = 8,
	PRESS_TO_LOGIN = 7,
	SERVER_PANEL = 9,
	CURRENT_SERVER = 11,
	TENCENT_LOGIN_VIEW = 3,
	AIRI_LOGIN_PANEL_VIEW = 4,
	YOSTAR_ALERT_VIEW = 6,
	LOGIN_PANEL_VIEW = 1
}
var_0_0.SWITCH_SUB_VIEW = "switch_sub_view"
var_0_0.CLEAR_REGISTER_VIEW = "clear_register_view"

return var_0_0
