local var_0_0 = class("PrayPoolConst")

var_0_0.SWITCH_TO_HOME_PAGE = "SWITCH_TO_HOME_PAGE"
var_0_0.SWITCH_TO_SELECT_POOL_PAGE = "SWITCH_TO_SELECT_POOL_PAGE"
var_0_0.SWITCH_TO_SELECT_SHIP_PAGE = "SWITCH_TO_SELECT_SHIP_PAGE"
var_0_0.CLICK_INDEX_BTN = "CLICK_INDEX_BTN"
var_0_0.CLICK_BUILD_BTN = "CLICK_BUILD_BTN"
var_0_0.START_BUILD_SHIP_EVENT = "START_BUILD_SHIP_EVENT"
var_0_0.BUILD_PRAY_POOL_CMD = "BUILD_PRAY_POOL_CMD"
var_0_0.BUILD_PRAY_POOL_SUCCESS = "BUILD_PRAY_POOL_SUCCESS"

return var_0_0
