local var_0_0 = class("EducateBaseUI", import("view.base.BaseUI"))

var_0_0.EDUCATE_GO_SCENE = "EDUCATE_GO_SCENE"
var_0_0.EDUCATE_CHANGE_SCENE = "EDUCATE_CHANGE_SCENE"
var_0_0.EDUCATE_GO_SUBLAYER = "EDUCATE_GO_SUBLAYER"
var_0_0.EDUCATE_ON_AWARD = "EDUCATE_ON_AWARD"
var_0_0.EDUCATE_ON_ITEM = "EDUCATE_ON_ITEM"
var_0_0.EDUCATE_ON_MSG_TIP = "EDUCATE_ON_MSG_TIP"
var_0_0.EDUCATE_ON_UNLOCK_TIP = "EDUCATE_ON_UNLOCK_TIP"

function var_0_0.getGroupName(arg_1_0)
	return LayerWeightConst.GROUP_EDUCATE
end

return var_0_0
