local var_0_0 = class("Fushun3GameEvent")

var_0_0.game_over_call = "game over call"
var_0_0.catch_item_call = "catch item call"
var_0_0.create_item_call = "create item call"
var_0_0.create_platform_item_call = "create platform item call"
var_0_0.item_follow_call = "item follow call"
var_0_0.create_monster_call = "create monster call"
var_0_0.player_attack_call = "player_attack_call"
var_0_0.check_player_damage = "check monster damage"
var_0_0.check_item_damage = "check item damage"
var_0_0.char_damaged_call = "char damaged call"
var_0_0.add_anim_effect_call = "add effect call"
var_0_0.add_effect_call = "add effect call"
var_0_0.power_speed_call = "power speed call"
var_0_0.add_monster_score_call = "add monster score call"
var_0_0.power_damage_monster_call = "power_damage_monster"
var_0_0.shot_damage_monster_call = "shot damage monster"
var_0_0.attack_damdage_monster_call = "attack damage monster"
var_0_0.kick_damage_monster_call = "kick damage monster"
var_0_0.script_jump_event = "fushun3 jump event "
var_0_0.script_attack_event = "fushun3 attake event"
var_0_0.script_power_event = "fushun3 power event"
var_0_0.day_night_change = "day night change"

return var_0_0
